### ISSUE TITLE
Add a Dialog/Modal

### ISSUE THREAD

**Issue by RodolfoSilva** [alex-min/live_view_native_flutter_client#6]
I was thinking about how we can implement a modal using live_components.

There are many possibilities today on the Flutter side. We can create a dialog, a new Route, or even use a Stack with Positioned to make a custom dialog...

Have you already implemented this using LVN, @alex-min? Do you have any advice on how to implement this?

**Comment by alex-min** [comment]
No there aren't any modal implementation at the moment in the codebase.

I was in favor of a server side event and on the client side it would push a dialog since modals are usually shown after user actions.

The code might support both as well, inline components and events.

I haven't thought too much about it yet.

**Comment by RodolfoSilva** [comment]
@alex-min, I think the main problem is keeping the communication between the modal and the page because sometimes you want to perform some actions inside the page after the modal closes. For example, a modal with filters that needs to be applied to the page.

**Comment by RodolfoSilva** [comment]
Perhaps having something like this would work:

```heex
<Dialog mode="page" show={booelan}>
   <.live_component id="xxx" module={MyModel} />
</Dialog>
```
And on the mobile side, we create a widget that initially renders nothing. However, when the show attribute is true, we can push a new route and render the content of the dialog inside this new route.

I think the main challenge here is keeping track of the updates, since the page that will be updated is the first one.

**Comment by alex-min** [comment]
We could use a global component for that, similar as what you have with the app bar, all of those are injected in the proper way into the MaterialApp and will behave well when switching pages. Modal would fit okay there.

**Comment by RodolfoSilva** [comment]
Can you guide me on how I can implement this? Then, I'll set it up here and send a PR for you to review. Regarding the last 2 PRs, is there anything else that needs to be done with them?

**Comment by alex-min** [comment]
@RodolfoSilva I'm sorry could you fix the conflicts in the second PR? I had to push some uncommitted changes I had for a while, I'm going to work in PRs as well on my side now since you are also working on it, this won't happen again.

For how global widgets are working, you can have a look at ```lib/live_view/ui/root_view/root_scaffold.dart```, all the ```StateChild.extractWidgetChild<LiveNavigationRail>(widgets);``` and similar lines at the top are extracting common widgets from the root.

The view works like this

```xml
<flutter>
  ... any global widget here...
  <viewBody>
  </viewBody>
</flutter>
```

The reason I'm doing it this way is to make sure the routing model is handled properly.

You can view some code examples here: https://live-view-flutter-pad.alex-min.fr/

**Comment by RodolfoSilva** [comment]
I've fixed the conflicts in the second PR.
Thanks, I'll take a look.

**Comment by alex-min** [comment]
thanks, I've also made the CI run on master, I'll fix anything which didn't work there

**Comment by alex-min** [comment]
@RodolfoSilva I've created a public slack to coordinate the efforts.

There's not a lot of documentation on this project yet so you'll need to ask questions for sure : https://join.slack.com/t/liveviewflutter/shared_invite/zt-2eyf5yq9v-x1J8Zr031UOCYFGNpLDv5g
